<style>
    @media only screen and (min-width: 320px)
        {
            .Head-bullet { top: 27px; left: 153px; }
    .Skull-bullet { top: 551px; left: 147px; }
    .Left-Eye-bullet { top: 38px; left: 163px; }
    .Right-Eye-bullet { top: 38px; left: 145px; }
    .Left-Ear-bullet { top: 43px; left: 175px; }
    .Right-Ear-bullet { top: 47px; left: 133px; }
    .Face-bullet { top: 45px; left: 144px; }
    .Nose-bullet { top: 45px; left: 154px; }
    .Mouth-bullet { top: 54px; left: 153px; }
    .Left-Shoulder-bullet { top: 89px; left: 181px; }
    .Right-Shoulder-bullet { top: 89px; left: 123px; }
    .Left-Arm-bullet { top: 131px; left: 204px; }
    .Right-Arm-bullet { top: 130px; left: 104px; }
    .Chest-bullet { top: 109px; left: 150px; }
    .Brain-bullet { top: 25px; left: 139px; }
    .Heart-bullet { top: 114px; left: 157px; }
    .Left-Lung-bullet { top: 140px; left: 174px; }
    .Right-Lung-bullet { top: 140px; left: 132px; }
    .Trachea-bullet { top: 75px; left: 154px; }
   
    .Upper-Abdomen-bullet { top: 151px; left: 152px; }
    .Lower-Abdomen-bullet { top: 195px; left: 152px; }
    .Pelvis-bullet { top: 211px; left: 152px; }
    .Buttocks-bullet { top: 755px; left: 180px; }
    .Groin-bullet { top: 224px; left: 160px; }
    .Left-Thigh-bullet { top: 270px; left: 170px; }
    .Right-Thigh-bullet { top: 270px; left: 134px; }
    .Left-Knee-bullet { top: 323px; left: 174px; }
    .Right-Knee-bullet { top: 321px; left: 135px; }
    .Left-Leg-bullet { top: 360px; left: 170px; }
    .Right-Leg-bullet { top: 360px; left: 136px; }
    .Left-Ankle-bullet { top: 415px; left: 158px; }
    .Right-Ankle-bullet { top: 414px; left: 133px; }
    .Left-Foot-bullet { top: 430px; left: 173px; }
    .Right-Foot-bullet { top: 430px; left: 130px; }

    .Left-Forearm-bullet { top: 176px; left: 236px; }
    .Right-Forearm-bullet { top: 178px; left: 77px; }
    .Left-Wrist-bullet { top: 724px; left: 49px; }
    .Right-Wrist-bullet { top: 730px; left: 259px; }
    .Left-Hand-bullet { top: 213px; left: 264px; }
    .Right-Hand-bullet { top: 218px; left: 49px; }
    .Cervical-Spine-bullet { top: 585px; left: 147px; }
    .Thoracic-Spine-bullet { top: 645px; left: 160px; }
    .Lumbar-Spine-bullet { top: 710px; left: 160px; }
    .Sacrum-bullet { top: 728px; left: 160px; }
    .Coccyx-bullet { top: 739px; left: 160px; }
    .Hips-bullet { top: 731px; left: 183px; }
    .Left-Elbow-bullet { top: 689px; left: 224px; }
    .Right-Elbow-bullet { top: 691px; left: 85px; } 

    /*For female highlight bullet point on body*/
    .female-Head-bullet { top: 27px; left: 153px; }
    .female-Skull-bullet { top: 568px; left: 129px; }
    .female-Left-Eye-bullet { top: 38px; left: 162px; }
    .female-Right-Eye-bullet { top: 38px; left: 147px; }
    .female-Left-Ear-bullet { top: 47px; left: 172px; }
    .female-Right-Ear-bullet { top: 47px; left: 136px; }
    .female-Face-bullet { top: 45px; left: 146px; }
    .female-Nose-bullet { top: 45px; left: 155px; }
    .female-Mouth-bullet { top: 54px; left: 155px; }
    .female-Left-Shoulder-bullet { top: 89px; left: 176px; }
    .female-Right-Shoulder-bullet { top: 91px; left: 126px; }
    .female-Left-Arm-bullet { top: 131px; left: 194px; }
    .female-Right-Arm-bullet { top: 130px; left: 115px; }
    .female-Chest-bullet { top: 109px; left: 150px; }
    .female-Brain-bullet { top: 25px; left: 139px; }
    .female-Heart-bullet { top: 114px; left: 156px; }
    .female-Left-Lung-bullet { top: 155px; left: 171px; }
    .female-Right-Lung-bullet { top: 155px; left: 137px; }
    .female-Trachea-bullet { top: 75px; left: 154px; }
   
    .female-Upper-Abdomen-bullet { top: 160px; left: 154px; }
    .female-Lower-Abdomen-bullet { top: 205px; left: 154px; }
    .female-Pelvis-bullet { top: 222px; left: 154px; }
    .female-Buttocks-bullet { top: 771px; left: 161px; }
    .female-Groin-bullet { top: 237px; left: 159px; }
    .female-Left-Thigh-bullet { top: 270px; left: 170px; }
    .female-Right-Thigh-bullet { top: 270px; left: 137px; }
    .female-Left-Knee-bullet { top: 346px; left: 172px; }
    .female-Right-Knee-bullet { top: 346px; left: 137px; }
    .female-Left-Leg-bullet { top: 401px; left: 167px; }
    .female-Right-Leg-bullet { top: 401px; left: 142px; }
    .female-Left-Ankle-bullet { top: 454px; left: 157px; }
    .female-Right-Ankle-bullet { top: 454px; left: 136px; }
    .female-Left-Foot-bullet { top: 474px; left: 170px; }
    .female-Right-Foot-bullet { top: 474px; left: 138px; }

    .female-Left-Forearm-bullet { top: 193px; left: 213px; }
    .female-Right-Forearm-bullet { top: 193px; left: 94px; }
    .female-Left-Wrist-bullet { top: 765px; left: 71px; }
    .female-Right-Wrist-bullet { top: 765px; left: 209px; }
    .female-Left-Hand-bullet { top: 242px; left: 230px; }
    .female-Right-Hand-bullet { top: 245px; left: 78px; }
    .female-Cervical-Spine-bullet { top: 600px; left: 130px; }
    .female-Thoracic-Spine-bullet { top: 645px; left: 137px; }
    .female-Lumbar-Spine-bullet { top: 710px; left: 137px; }
    .female-Sacrum-bullet { top: 742px; left: 137px; }
    .female-Coccyx-bullet { top: 753px; left: 137px; }
    .female-Hips-bullet { top: 744px; left: 171px; }
    .female-Left-Elbow-bullet { top: 705px; left: 85px; }
    .female-Right-Elbow-bullet { top: 708px; left: 201px; }

    /*For female highlight bullet point on body*/
    }
    @media only screen and (min-width: 375px)
        {
        .Head-bullet { top: 27px; left: 180px; }
    .Skull-bullet { top: 551px; left: 173px; }
    .Left-Eye-bullet { top: 38px; left: 190px; }
    .Right-Eye-bullet { top: 38px; left: 172px; }
    .Left-Ear-bullet { top: 43px; left: 205px; }
    .Right-Ear-bullet { top: 47px; left: 158px; }
    .Face-bullet { top: 45px; left: 169px; }
    .Nose-bullet { top: 45px; left: 181px; }
    .Mouth-bullet { top: 54px; left: 181px; }
    .Left-Shoulder-bullet { top: 89px; left: 211px; }
    .Right-Shoulder-bullet { top: 89px; left: 140px; }
    .Left-Arm-bullet { top: 131px; left: 242px; }
    .Right-Arm-bullet { top: 130px; left: 119px; }
    .Chest-bullet { top: 109px; left: 178px; }
    .Brain-bullet { top: 25px; left: 163px; }
    .Heart-bullet { top: 114px; left: 185px; }
    .Left-Lung-bullet { top: 140px; left: 206px; }
    .Right-Lung-bullet { top: 140px; left: 155px; }
    .Trachea-bullet { top: 75px; left: 181px; }
   
    .Upper-Abdomen-bullet { top: 151px; left: 179px; }
    .Lower-Abdomen-bullet { top: 195px; left: 179px; }
    .Pelvis-bullet { top: 211px; left: 179px; }
    .Buttocks-bullet { top: 755px; left: 210px; }
    .Groin-bullet { top: 224px; left: 187px; }
    .Left-Thigh-bullet { top: 270px; left: 200px; }
    .Right-Thigh-bullet { top: 270px; left: 161px; }
    .Left-Knee-bullet { top: 323px; left: 203px; }
    .Right-Knee-bullet { top: 321px; left: 158px; }
    .Left-Leg-bullet { top: 360px; left: 201px; }
    .Right-Leg-bullet { top: 360px; left: 161px; }
    .Left-Ankle-bullet { top: 415px; left: 188px; }
    .Right-Ankle-bullet { top: 414px; left: 156px; }
    .Left-Foot-bullet { top: 430px; left: 204px; }
    .Right-Foot-bullet { top: 430px; left: 153px; }

    .Left-Forearm-bullet { top: 176px; left: 280px; }
    .Right-Forearm-bullet { top: 178px; left: 86px; }
    .Left-Wrist-bullet { top: 724px; left: 59px; }
    .Right-Wrist-bullet { top: 730px; left: 305px; }
    .Left-Hand-bullet { top: 213px; left: 313px; }
    .Right-Hand-bullet { top: 218px; left: 57px; }
    .Cervical-Spine-bullet { top: 585px; left: 172px; }
    .Thoracic-Spine-bullet { top: 645px; left: 188px; }
    .Lumbar-Spine-bullet { top: 710px; left: 188px; }
    .Sacrum-bullet { top: 728px; left: 188px; }
    .Coccyx-bullet { top: 739px; left: 188px; }
    .Hips-bullet { top: 731px; left: 216px; }
    .Left-Elbow-bullet { top: 689px; left: 104px; }
    .Right-Elbow-bullet { top: 691px; left: 267px; }

    /*For female highlight bullet point on body*/
    .female-Head-bullet { top: 27px; left: 181px; }
    .female-Skull-bullet { top: 568px; left: 151px; }
    .female-Left-Eye-bullet { top: 38px; left: 190px; }
    .female-Right-Eye-bullet { top: 38px; left: 173px; }
    .female-Left-Ear-bullet { top: 47px; left: 203px; }
    .female-Right-Ear-bullet { top: 47px; left: 162px; }
    .female-Face-bullet { top: 45px; left: 172px; }
    .female-Nose-bullet { top: 45px; left: 182px; }
    .female-Mouth-bullet { top: 54px; left: 182px; }
    .female-Left-Shoulder-bullet { top: 89px; left: 212px; }
    .female-Right-Shoulder-bullet { top: 91px; left: 148px; }
    .female-Left-Arm-bullet { top: 131px; left: 229px; }
    .female-Right-Arm-bullet { top: 130px; left: 135px; }
    .female-Chest-bullet { top: 109px; left: 177px; }
    .female-Brain-bullet { top: 25px; left: 164px; }
    .female-Heart-bullet { top: 114px; left: 184px; }
    .female-Left-Lung-bullet { top: 155px; left: 201px; }
    .female-Right-Lung-bullet { top: 155px; left: 162px; }
    .female-Trachea-bullet { top: 75px; left: 181px; }
   
    .female-Upper-Abdomen-bullet { top: 160px; left: 181px; }
    .female-Lower-Abdomen-bullet { top: 205px; left: 181px; }
    .female-Pelvis-bullet { top: 222px; left: 181px; }
    .female-Buttocks-bullet { top: 771px; left: 187px; }
    .female-Groin-bullet { top: 237px; left: 189px; }
    .female-Left-Thigh-bullet { top: 270px; left: 198px; }
    .female-Right-Thigh-bullet { top: 270px; left: 163px; }
    .female-Left-Knee-bullet { top: 346px; left: 202px; }
    .female-Right-Knee-bullet { top: 346px; left: 162px; }
    .female-Left-Leg-bullet { top: 401px; left: 197px; }
    .female-Right-Leg-bullet { top: 401px; left: 166px; }
    .female-Left-Ankle-bullet { top: 454px; left: 186px; }
    .female-Right-Ankle-bullet { top: 454px; left: 160px; }
    .female-Left-Foot-bullet { top: 474px; left: 201px; }
    .female-Right-Foot-bullet { top: 474px; left: 162px; }

    .female-Left-Forearm-bullet { top: 193px; left: 252px; }
    .female-Right-Forearm-bullet { top: 193px; left: 110px; }
    .female-Left-Wrist-bullet { top: 765px; left: 83px; }
    .female-Right-Wrist-bullet { top: 765px; left: 247px; }
    .female-Left-Hand-bullet { top: 242px; left: 272px; }
    .female-Right-Hand-bullet { top: 245px; left: 90px; }
    .female-Cervical-Spine-bullet { top: 600px; left: 154px; }
    .female-Thoracic-Spine-bullet { top: 645px; left: 164px; }
    .female-Lumbar-Spine-bullet { top: 710px; left: 163px; }
    .female-Sacrum-bullet { top: 742px; left: 163px; }
    .female-Coccyx-bullet { top: 753px; left: 163px; }
    .female-Hips-bullet { top: 744px; left: 200px; }
    .female-Left-Elbow-bullet { top: 705px; left: 100px; }
    .female-Right-Elbow-bullet { top: 708px; left: 238px; }

    /*For female highlight bullet point on body*/  
    }
    @media only screen and (min-width: 425px)
        {
            .Head-bullet { top: 27px; left: 205px; }
    .Skull-bullet { top: 551px; left: 197px; }
    .Left-Eye-bullet { top: 38px; left: 217px; }
    .Right-Eye-bullet { top: 38px; left: 194px; }
    .Left-Ear-bullet { top: 43px; left: 232px; }
    .Right-Ear-bullet { top: 47px; left: 179px; }
    .Face-bullet { top: 45px; left: 192px; }
    .Nose-bullet { top: 45px; left: 205px; }
    .Mouth-bullet { top: 54px; left: 206px; }
    .Left-Shoulder-bullet { top: 89px; left: 247px; }
    .Right-Shoulder-bullet { top: 89px; left: 161px; }
    .Left-Arm-bullet { top: 131px; left: 274px; }
    .Right-Arm-bullet { top: 130px; left: 139px; }
    .Chest-bullet { top: 109px; left: 203px; }
    .Brain-bullet { top: 25px; left: 185px; }
    .Heart-bullet { top: 114px; left: 210px; }
    .Left-Lung-bullet { top: 140px; left: 233px; }
    .Right-Lung-bullet { top: 140px; left: 176px; }
    .Trachea-bullet { top: 75px; left: 204px; }
   
    .Upper-Abdomen-bullet { top: 151px; left: 203px; }
    .Lower-Abdomen-bullet { top: 195px; left: 203px; }
    .Pelvis-bullet { top: 211px; left: 203px; }
    .Buttocks-bullet { top: 755px; left: 240px; }
    .Groin-bullet { top: 224px; left: 215px; }
    .Left-Thigh-bullet { top: 270px; left: 230px; }
    .Right-Thigh-bullet { top: 270px; left: 175px; }
    .Left-Knee-bullet { top: 323px; left: 233px; }
    .Right-Knee-bullet { top: 321px; left: 179px; }
    .Left-Leg-bullet { top: 360px; left: 228px; }
    .Right-Leg-bullet { top: 360px; left: 183px; }
    .Left-Ankle-bullet { top: 415px; left: 214px; }
    .Right-Ankle-bullet { top: 414px; left: 179px; }
    .Left-Foot-bullet { top: 430px; left: 231px; }
    .Right-Foot-bullet { top: 430px; left: 176px; }

    .Left-Forearm-bullet { top: 176px; left: 317px; }
    .Right-Forearm-bullet { top: 178px; left: 100px; }
    .Left-Wrist-bullet { top: 724px; left: 68px; }
    .Right-Wrist-bullet { top: 730px; left: 349px; }
    .Left-Hand-bullet { top: 213px; left: 357px; }
    .Right-Hand-bullet { top: 218px; left: 65px; }
    .Cervical-Spine-bullet { top: 585px; left: 195px; }
    .Thoracic-Spine-bullet { top: 645px; left: 213px; }
    .Lumbar-Spine-bullet { top: 710px; left: 213px; }
    .Sacrum-bullet { top: 728px; left: 213px; }
    .Coccyx-bullet { top: 739px; left: 213px; }
    .Hips-bullet { top: 731px; left: 246px; }
    .Left-Elbow-bullet { top: 689px; left: 116px; }
    .Right-Elbow-bullet { top: 691px; left: 304px; }

    /*For female highlight bullet point on body*/
    .female-Head-bullet { top: 27px; left: 206px; }
    .female-Skull-bullet { top: 568px; left: 172px; }
    .female-Left-Eye-bullet { top: 38px; left: 217px; }
    .female-Right-Eye-bullet { top: 38px; left: 197px; }
    .female-Left-Ear-bullet { top: 47px; left: 231px; }
    .female-Right-Ear-bullet { top: 47px; left: 183px; }
    .female-Face-bullet { top: 45px; left: 195px; }
    .female-Nose-bullet { top: 45px; left: 207px; }
    .female-Mouth-bullet { top: 54px; left: 207px; }
    .female-Left-Shoulder-bullet { top: 89px; left: 243px; }
    .female-Right-Shoulder-bullet { top: 91px; left: 163px; }
    .female-Left-Arm-bullet { top: 131px; left: 259px; }
    .female-Right-Arm-bullet { top: 130px; left: 153px; }
    .female-Chest-bullet { top: 109px; left: 203px; }
    .female-Brain-bullet { top: 25px; left: 187px; }
    .female-Heart-bullet { top: 114px; left: 210px; }
    .female-Left-Lung-bullet { top: 155px; left: 231px; }
    .female-Right-Lung-bullet { top: 155px; left: 184px; }
    .female-Trachea-bullet { top: 75px; left: 205px; }
   
    .female-Upper-Abdomen-bullet { top: 160px; left: 207px; }
    .female-Lower-Abdomen-bullet { top: 205px; left: 207px; }
    .female-Pelvis-bullet { top: 222px; left: 207px; }
    .female-Buttocks-bullet { top: 771px; left: 214px; }
    .female-Groin-bullet { top: 237px; left: 216px; }
    .female-Left-Thigh-bullet { top: 270px; left: 228px; }
    .female-Right-Thigh-bullet { top: 270px; left: 182px; }
    .female-Left-Knee-bullet { top: 346px; left: 231px; }
    .female-Right-Knee-bullet { top: 346px; left: 184px; }
    .female-Left-Leg-bullet { top: 401px; left: 223px; }
    .female-Right-Leg-bullet { top: 401px; left: 189px; }
    .female-Left-Ankle-bullet { top: 454px; left: 212px; }
    .female-Right-Ankle-bullet { top: 454px; left: 182px; }
    .female-Left-Foot-bullet { top: 474px; left: 228px; }
    .female-Right-Foot-bullet { top: 474px; left: 184px; }

    .female-Left-Forearm-bullet { top: 193px; left: 285px; }
    .female-Right-Forearm-bullet { top: 193px; left: 126px; }
    .female-Left-Wrist-bullet { top: 765px; left: 94px; }
    .female-Right-Wrist-bullet { top: 765px; left: 281px; }
    .female-Left-Hand-bullet { top: 242px; left: 311px; }
    .female-Right-Hand-bullet { top: 245px; left: 102px; }
    .female-Cervical-Spine-bullet { top: 600px; left: 178px; }
    .female-Thoracic-Spine-bullet { top: 645px; left: 187px; }
    .female-Lumbar-Spine-bullet { top: 710px; left: 186px; }
    .female-Sacrum-bullet { top: 742px; left: 186px; }
    .female-Coccyx-bullet { top: 753px; left: 186px; }
    .female-Hips-bullet { top: 744px; left: 233px; }
    .female-Left-Elbow-bullet { top: 705px; left: 114px; }
    .female-Right-Elbow-bullet { top: 708px; left: 272px; }

    /*For female highlight bullet point on body*/
    }
    @media only screen and (min-width: 768px)
    {
        .Head-bullet { top: 27px; left: 90px; }
    .Skull-bullet { top: 551px; left: 87px; }
    .Left-Eye-bullet { top: 38px; left: 98px; }
    .Right-Eye-bullet { top: 38px; left: 82px; }
    .Left-Ear-bullet { top: 43px; left: 102px; }
    .Right-Ear-bullet { top: 47px; left: 80px; }
    .Face-bullet { top: 45px; left: 82px; }
    .Nose-bullet { top: 45px; left: 90px; }
    .Mouth-bullet { top: 54px; left: 91px; }
    .Left-Shoulder-bullet { top: 89px; left: 107px; }
    .Right-Shoulder-bullet { top: 89px; left: 71px; }
    .Left-Arm-bullet { top: 131px; left: 119px; }
    .Right-Arm-bullet { top: 130px; left: 62px; }
    .Chest-bullet { top: 109px; left: 87px; }
    .Brain-bullet { top: 25px; left: 80px; }
    .Heart-bullet { top: 114px; left: 92px; }
    .Left-Lung-bullet { top: 140px; left: 103px; }
    .Right-Lung-bullet { top: 140px; left: 74px; }
    .Trachea-bullet { top: 75px; left: 89px; }
   
    .Upper-Abdomen-bullet { top: 151px; left: 90px; }
    .Lower-Abdomen-bullet { top: 195px; left: 90px; }
    .Pelvis-bullet { top: 211px; left: 90px; }
    .Buttocks-bullet { top: 755px; left: 105px; }
    .Groin-bullet { top: 224px; left: 96px; }
    .Left-Thigh-bullet { top: 270px; left: 102px; }
    .Right-Thigh-bullet { top: 270px; left: 79px; }
    .Left-Knee-bullet { top: 323px; left: 101px; }
    .Right-Knee-bullet { top: 321px; left: 78px; }
    .Left-Leg-bullet { top: 360px; left: 99px; }
    .Right-Leg-bullet { top: 360px; left: 82px; }
    .Left-Ankle-bullet { top: 415px; left: 94px; }
    .Right-Ankle-bullet { top: 414px; left: 78px; }
    .Left-Foot-bullet { top: 430px; left: 100px; }
    .Right-Foot-bullet { top: 430px; left: 77px; }

    .Left-Forearm-bullet { top: 176px; left: 134px; }
    .Right-Forearm-bullet { top: 178px; left: 48px; }
    .Left-Wrist-bullet { top: 724px; left: 33px; }
    .Right-Wrist-bullet { top: 730px; left: 151px; }
    .Left-Hand-bullet { top: 213px; left: 151px; }
    .Right-Hand-bullet { top: 218px; left: 32px; }
    .Cervical-Spine-bullet { top: 585px; left: 83px; }
    .Thoracic-Spine-bullet { top: 645px; left: 92px; }
    .Lumbar-Spine-bullet { top: 710px; left: 93px; }
    .Sacrum-bullet { top: 728px; left: 94px; }
    .Coccyx-bullet { top: 739px; left: 94px; }
    .Hips-bullet { top: 731px; left: 107px; }
    .Left-Elbow-bullet { top: 689px; left: 53px; }
    .Right-Elbow-bullet { top: 691px; left: 132px; }

    /*For female highlight bullet point on body*/
    .female-Head-bullet { top: 27px; left: 90px; }
    .female-Skull-bullet { top: 568px; left: 76px; }
    .female-Left-Eye-bullet { top: 38px; left: 96px; }
    .female-Right-Eye-bullet { top: 38px; left: 85px; }
    .female-Left-Ear-bullet { top: 47px; left: 102px; }
    .female-Right-Ear-bullet { top: 47px; left: 78px; }
    .female-Face-bullet { top: 45px; left: 83px; }
    .female-Nose-bullet { top: 45px; left: 91px; }
    .female-Mouth-bullet { top: 54px; left: 91px; }
    .female-Left-Shoulder-bullet { top: 89px; left: 110px; }
    .female-Right-Shoulder-bullet { top: 91px; left: 75px; }
    .female-Left-Arm-bullet { top: 131px; left: 113px; }
    .female-Right-Arm-bullet { top: 130px; left: 67px; }
    .female-Chest-bullet { top: 109px; left: 87px; }
    .female-Brain-bullet { top: 25px; left: 80px; }
    .female-Heart-bullet { top: 114px; left: 92px; }
    .female-Left-Lung-bullet { top: 155px; left: 99px; }
    .female-Right-Lung-bullet { top: 155px; left: 80px; }
    .female-Trachea-bullet { top: 75px; left: 91px; }
   
    .female-Upper-Abdomen-bullet { top: 160px; left: 90px; }
    .female-Lower-Abdomen-bullet { top: 205px; left: 90px; }
    .female-Pelvis-bullet { top: 222px; left: 90px; }
    .female-Buttocks-bullet { top: 771px; left: 97px; }
    .female-Groin-bullet { top: 237px; left: 95px; }
    .female-Left-Thigh-bullet { top: 270px; left: 103px; }
    .female-Right-Thigh-bullet { top: 270px; left: 81px; }
    .female-Left-Knee-bullet { top: 346px; left: 101px; }
    .female-Right-Knee-bullet { top: 346px; left: 82px; }
    .female-Left-Leg-bullet { top: 401px; left: 99px; }
    .female-Right-Leg-bullet { top: 401px; left: 83px; }
    .female-Left-Ankle-bullet { top: 454px; left: 93px; }
    .female-Right-Ankle-bullet { top: 454px; left: 78px; }
    .female-Left-Foot-bullet { top: 474px; left: 99px; }
    .female-Right-Foot-bullet { top: 474px; left: 81px; }

    .female-Left-Forearm-bullet { top: 193px; left: 124px; }
    .female-Right-Forearm-bullet { top: 193px; left: 57px; }
    .female-Left-Wrist-bullet { top: 765px; left: 45px; }
    .female-Right-Wrist-bullet { top: 765px; left: 121px; }
    .female-Left-Hand-bullet { top: 242px; left: 132px; }
    .female-Right-Hand-bullet { top: 245px; left: 49px; }
    .female-Cervical-Spine-bullet { top: 600px; left: 76px; }
    .female-Thoracic-Spine-bullet { top: 645px; left: 83px; }
    .female-Lumbar-Spine-bullet { top: 710px; left: 83px; }
    .female-Sacrum-bullet { top: 742px; left: 83px; }
    .female-Coccyx-bullet { top: 753px; left: 83px; }
    .female-Hips-bullet { top: 744px; left: 101px; }
    .female-Left-Elbow-bullet { top: 705px; left: 54px; }
    .female-Right-Elbow-bullet { top: 708px; left: 118px; }

    /*For female highlight bullet point on body*/
        
    } 
    @media only screen and (min-width: 1024px)
    {
        /******** for 1024 Resolution  ********/
    .Head-bullet { top: 27px; left: 93px; }
    .Skull-bullet { top: 551px; left: 90px; }
    .Left-Eye-bullet { top: 38px; left: 85px; }
    .Right-Eye-bullet { top: 38px; left: 100px; }
    .Left-Ear-bullet { top: 43px; left: 79px; }
    .Right-Ear-bullet { top: 47px; left: 108px; }
    .Face-bullet { top: 45px; left: 86px; }
    .Nose-bullet { top: 45px; left: 94px; }
    .Mouth-bullet { top: 54px; left: 95px; }
    .Left-Shoulder-bullet { top: 89px; left: 111px; }
    .Right-Shoulder-bullet { top: 89px; left: 76px; }
    .Left-Arm-bullet { top: 131px; left: 124px; }
    .Right-Arm-bullet { top: 130px; left: 65px; }
    .Chest-bullet { top: 109px; left: 92px; }
    .Brain-bullet { top: 25px; left: 83px; }
    .Heart-bullet { top: 114px; left: 96px; }
    .Left-Lung-bullet { top: 140px; left: 109px; }
    .Right-Lung-bullet { top: 140px; left: 79px; }
    .Trachea-bullet { top: 75px; left: 94px; }
   
    .Upper-Abdomen-bullet { top: 151px; left: 97px; }
    .Lower-Abdomen-bullet { top: 195px; left: 95px; }
    .Pelvis-bullet { top: 211px; left: 95px; }
    .Buttocks-bullet { top: 755px; left: 108px; }
    .Groin-bullet { top: 224px; left: 100px; }
    .Left-Thigh-bullet { top: 270px; left: 107px; }
    .Right-Thigh-bullet { top: 270px; left: 82px; }
    .Left-Knee-bullet { top: 323px; left: 106px; }
    .Right-Knee-bullet { top: 321px; left: 83px; }
    .Left-Leg-bullet { top: 360px; left: 104px; }
    .Right-Leg-bullet { top: 360px; left: 85px; }
    .Left-Ankle-bullet { top: 415px; left: 99px; }
    .Right-Ankle-bullet { top: 414px; left: 81px; }
    .Left-Foot-bullet { top: 430px; left: 105px; }
    .Right-Foot-bullet { top: 430px; left: 81px; }

    .Left-Forearm-bullet { top: 176px; left: 141px; }
    .Right-Forearm-bullet { top: 178px; left: 50px; }
    .Left-Wrist-bullet { top: 724px; left: 35px; }
    .Right-Wrist-bullet { top: 730px; left: 156px; }
    .Left-Hand-bullet { top: 213px; left: 160px; }
    .Right-Hand-bullet { top: 218px; left: 33px; }
    .Cervical-Spine-bullet { top: 585px; left: 88px; }
    .Thoracic-Spine-bullet { top: 645px; left: 97px; }
    .Lumbar-Spine-bullet { top: 710px; left: 98px; }
    .Sacrum-bullet { top: 731px; left: 98px; }
    .Coccyx-bullet { top: 742px; left: 98px; }
    .Hips-bullet { top: 731px; left: 157px; }
    .Left-Elbow-bullet { top: 689px; left: 57px; }
    .Right-Elbow-bullet { top: 691px; left: 137px; }

    /*For female highlight bullet point on body*/
    .female-Head-bullet { top: 27px; left: 95px; }
    .female-Skull-bullet { top: 568px; left: 80px; }
    .female-Left-Eye-bullet { top: 38px; left: 102px; }
    .female-Right-Eye-bullet { top: 38px; left: 89px; }
    .female-Left-Ear-bullet { top: 47px; left: 106px; }
    .female-Right-Ear-bullet { top: 47px; left: 84px; }
    .female-Face-bullet { top: 45px; left: 88px; }
    .female-Nose-bullet { top: 45px; left: 96px; }
    .female-Mouth-bullet { top: 54px; left: 95px; }
    .female-Left-Shoulder-bullet { top: 89px; left: 113px; }
    .female-Right-Shoulder-bullet { top: 91px; left: 75px; }
    .female-Left-Arm-bullet { top: 131px; left: 119px; }
    .female-Right-Arm-bullet { top: 130px; left: 70px; }
    .female-Chest-bullet { top: 109px; left: 91px; }
    .female-Brain-bullet { top: 25px; left: 85px; }
    .female-Heart-bullet { top: 114px; left: 97px; }
    .female-Left-Lung-bullet { top: 155px; left: 104px; }
    .female-Right-Lung-bullet { top: 155px; left: 84px; }
    .female-Trachea-bullet { top: 75px; left: 95px; }
   
    .female-Upper-Abdomen-bullet { top: 160px; left: 95px; }
    .female-Lower-Abdomen-bullet { top: 205px; left: 95px; }
    .female-Pelvis-bullet { top: 222px; left: 95px; }
    .female-Buttocks-bullet { top: 771px; left: 100px; }
    .female-Groin-bullet { top: 237px; left: 101px; }
    .female-Left-Thigh-bullet { top: 270px; left: 110px; }
    .female-Right-Thigh-bullet { top: 270px; left: 85px; }
    .female-Left-Knee-bullet { top: 346px; left: 105px; }
    .female-Right-Knee-bullet { top: 346px; left: 85px; }
    .female-Left-Leg-bullet { top: 401px; left: 104px; }
    .female-Right-Leg-bullet { top: 401px; left: 88px; }
    .female-Left-Ankle-bullet { top: 454px; left: 97px; }
    .female-Right-Ankle-bullet { top: 454px; left: 83px; }
    .female-Left-Foot-bullet { top: 474px; left: 105px; }
    .female-Right-Foot-bullet { top: 474px; left: 85px; }

    .female-Left-Forearm-bullet { top: 193px; left: 130px; }
    .female-Right-Forearm-bullet { top: 193px; left: 59px; }
    .female-Left-Wrist-bullet { top: 765px; left: 46px; }
    .female-Right-Wrist-bullet { top: 765px; left: 128px; }
    .female-Left-Hand-bullet { top: 242px; left: 140px; }
    .female-Right-Hand-bullet { top: 245px; left: 52px; }
    .female-Cervical-Spine-bullet { top: 600px; left: 78px; }
    .female-Thoracic-Spine-bullet { top: 645px; left: 86px; }
    .female-Lumbar-Spine-bullet { top: 710px; left: 86px; }
    .female-Sacrum-bullet { top: 742px; left: 86px; }
    .female-Coccyx-bullet { top: 753px; left: 86px; }
    .female-Hips-bullet { top: 744px; left: 104px; }
    .female-Left-Elbow-bullet { top: 705px; left: 54px; }
    .female-Right-Elbow-bullet { top: 708px; left: 122px; }

    /*For female highlight bullet point on body*/
    }
    @media only screen and (min-width: 1320px)
        {
        .Head-bullet { top: 27px; left: 132px; }
    .Skull-bullet { top: 551px; left: 130px; }
    .Left-Eye-bullet { top: 38px; left: 125px; }
    .Right-Eye-bullet { top: 38px; left: 140px; }
    .Left-Ear-bullet { top: 47px; left: 149px; }
    .Right-Ear-bullet { top: 47px; left: 115px; }
    .Face-bullet { top: 45px; left: 121px; }
    .Nose-bullet { top: 45px; left: 131px; }
    .Mouth-bullet { top: 54px; left: 131px; }
    .Left-Shoulder-bullet { top: 89px; left: 158px; }
    .Right-Shoulder-bullet { top: 93px; left: 90px; }
    .Left-Arm-bullet { top: 131px; left: 176px; }
    .Right-Arm-bullet { top: 130px; left: 86px; }
    .Chest-bullet { top: 109px; left: 131px; }
    .Brain-bullet { top: 25px; left: 119px; }
    .Heart-bullet { top: 114px; left: 138px; }
    .Left-Lung-bullet { top: 140px; left: 146px; }
    .Right-Lung-bullet { top: 140px; left: 121px; }
    .Trachea-bullet { top: 75px; left: 130px; }
   
    .Upper-Abdomen-bullet { top: 151px; left: 134px; }
    .Lower-Abdomen-bullet { top: 195px; left: 133px; }
    .Pelvis-bullet { top: 211px; left: 131px; }
    .Buttocks-bullet { top: 755px; left: 153px; }
    .Groin-bullet { top: 224px; left: 140px; }
    .Left-Thigh-bullet { top: 270px; left: 146px; }
    .Right-Thigh-bullet { top: 270px; left: 110px; }
    .Left-Knee-bullet { top: 323px; left: 148px; }
    .Right-Knee-bullet { top: 320px; left: 115px; }
    .Left-Leg-bullet { top: 360px; left: 144px; }
    .Right-Leg-bullet { top: 360px; left: 116px; }
    .Left-Ankle-bullet { top: 415px; left: 135px; }
    .Right-Ankle-bullet { top: 414px; left: 115px; }
    .Left-Foot-bullet { top: 430px; left: 147px; }
    .Right-Foot-bullet { top: 430px; left: 112px; }

    .Left-Forearm-bullet { top: 176px; left: 199px; }
    .Right-Forearm-bullet { top: 178px; left: 66px; }
    .Left-Wrist-bullet { top: 724px; left: 45px; }
    .Right-Wrist-bullet { top: 730px; left: 222px; }
    .Left-Hand-bullet { top: 213px; left: 226px; }
    .Right-Hand-bullet { top: 218px; left: 44px; }
    .Cervical-Spine-bullet { top: 585px; left: 125px; }
    .Thoracic-Spine-bullet { top: 645px; left: 135px; }
    .Lumbar-Spine-bullet { top: 710px; left: 131px; }
    .Sacrum-bullet { top: 731px; left: 135px; }
    .Coccyx-bullet { top: 742px; left: 134px; }
    .Hips-bullet { top: 731px; left: 157px; }
    .Left-Elbow-bullet { top: 689px; left: 79px; }
    .Right-Elbow-bullet { top: 691px; left: 191px; }

    /*For female highlight bullet point on body*/
    .female-Head-bullet { top: 27px; left: 133px; }
    .female-Skull-bullet { top: 568px; left: 111px; }
    .female-Left-Eye-bullet { top: 38px; left: 140px; }
    .female-Right-Eye-bullet { top: 38px; left: 126px; }
    .female-Left-Ear-bullet { top: 47px; left: 150px; }
    .female-Right-Ear-bullet { top: 47px; left: 117px; }
    .female-Face-bullet { top: 45px; left: 124px; }
    .female-Nose-bullet { top: 45px; left: 133px; }
    .female-Mouth-bullet { top: 54px; left: 133px; }
    .female-Left-Shoulder-bullet { top: 89px; left: 155px; }
    .female-Right-Shoulder-bullet { top: 91px; left: 113px; }
    .female-Left-Arm-bullet { top: 131px; left: 167px; }
    .female-Right-Arm-bullet { top: 130px; left: 99px; }
    .female-Chest-bullet { top: 109px; left: 131px; }
    .female-Brain-bullet { top: 25px; left: 120px; }
    .female-Heart-bullet { top: 114px; left: 138px; }
    .female-Left-Lung-bullet { top: 155px; left: 146px; }
    .female-Right-Lung-bullet { top: 155px; left: 121px; }
    .female-Trachea-bullet { top: 75px; left: 132px; }
   
    .female-Upper-Abdomen-bullet { top: 160px; left: 134px; }
    .female-Lower-Abdomen-bullet { top: 205px; left: 133px; }
    .female-Pelvis-bullet { top: 222px; left: 133px; }
    .female-Buttocks-bullet { top: 771px; left: 140px; }
    .female-Groin-bullet { top: 237px; left: 140px; }
    .female-Left-Thigh-bullet { top: 270px; left: 146px; }
    .female-Right-Thigh-bullet { top: 270px; left: 110px; }
    .female-Left-Knee-bullet { top: 346px; left: 147px; }
    .female-Right-Knee-bullet { top: 346px; left: 118px; }
    .female-Left-Leg-bullet { top: 401px; left: 144px; }
    .female-Right-Leg-bullet { top: 401px; left: 120px; }
    .female-Left-Ankle-bullet { top: 454px; left: 136px; }
    .female-Right-Ankle-bullet { top: 454px; left: 117px; }
    .female-Left-Foot-bullet { top: 474px; left: 147px; }
    .female-Right-Foot-bullet { top: 474px; left: 117px; }

    .female-Left-Forearm-bullet { top: 193px; left: 183px; }
    .female-Right-Forearm-bullet { top: 193px; left: 82px; }
    .female-Left-Wrist-bullet { top: 765px; left: 62px; }
    .female-Right-Wrist-bullet { top: 765px; left: 180px; }
    .female-Left-Hand-bullet { top: 242px; left: 197px; }
    .female-Right-Hand-bullet { top: 245px; left: 67px; }
    .female-Cervical-Spine-bullet { top: 600px; left: 113px; }
    .female-Thoracic-Spine-bullet { top: 645px; left: 120px; }
    .female-Lumbar-Spine-bullet { top: 710px; left: 120px; }
    .female-Sacrum-bullet { top: 742px; left: 120px; }
    .female-Coccyx-bullet { top: 753px; left: 120px; }
    .female-Hips-bullet { top: 744px; left: 148px; }
    .female-Left-Elbow-bullet { top: 705px; left: 76px; }
    .female-Right-Elbow-bullet { top: 708px; left: 170px; }

    /*For female highlight bullet point on body*/    
    }
</style>